# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hhm2MlrHsH5q2ObxXZvXZ70rb3RKzzM9
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

data = pd.read_csv("brain_stroke.csv")

data.head()

data.shape

missing_values = data.isnull().sum()
missing_values

categorical_cols = ['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

df_encoded = pd.get_dummies(data, columns=categorical_cols)

df_encoded.head()

df_encoded.shape

x = df_encoded.drop(columns=['smoking_status_smokes','smoking_status_never smoked','smoking_status_formerly smoked','smoking_status_Unknown'])
y= df_encoded['stroke']

x

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.40,random_state=0)

model = RandomForestClassifier(random_state=0)

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

accuracy